/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{ts,tsx}",
        "./components/**/*.{ts,tsx}",
        "./app/**/*.{ts,tsx}",
        "./src/**/*.{ts,tsx}",
        "./stories/**/*.{ts,tsx}",
    ],
    prefix: "",
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        screens: {
            sm: "780px",
            md: "1420px",
        },
        extend: {
            colors: {
                neutral_100: "#ffffff",
                neutral_200: "#fdfdfd",
                neutral_300: "#f5f5f5",
                neutral_400: "#f0f0f0",
                neutral_500: "#dbdbdb",
                neutral_600: "#c3c3c3",
                neutral_700: "#929292",
                neutral_800: "#626262",
                neutral_900: "#4e4e4e",
                neutral_1000: "#313131",
                neutral_1100: "#2a2a2a",
                neutral_1200: "#202020",
                neutral_1300: "#0d0d0d",
                primary_50: "#fcf0ea",
                primary_100: "#f5d1bd",
                primary_200: "#f0bb9d",
                primary_300: "#e99d70",
                primary_400: "#e58955",
                primary_500: "#de6c2a",
                primary_600: "#ca6226",
                primary_700: "#9e4d1e",
                primary_800: "#7a3b17",
                primary_900: "#5d2d12",
                secondary_50: "#eafefe",
                secondary_100: "#befbfb",
                secondary_200: "#9ff9f9",
                secondary_300: "#73f6f6",
                secondary_400: "#58f5f4",
                secondary_500: "#2ef2f1",
                secondary_600: "#2adcdb",
                secondary_700: "#21acab",
                secondary_800: "#198585",
                secondary_900: "#136665",
                warning: "#f5a524",
                fail: "#f31260",
                success: "#18c964",
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
